services:
  gw-server:
    image: gateway-server:latest
    build:
      context: ./
      dockerfile: ../shell/server-docker/gateway/Dockerfile
    networks:
      - study-test-net
    ports:
      - "8761:8761"
      - "18081:18081"
    
  business-service:
    image: business-service:latest
    build:
      context: ./
      dockerfile: ../shell/server-docker/business/Dockerfile
    networks:
      - study-test-net
    depends_on:
      - gw-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://gw-server:8761/eureka/
